name: audiobooks
description: 'Listen to your favorite audiobooks for free!'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
    sdk: '>=3.3.1 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

    connectivity_plus: ^6.0.1
    dio: ^5.4.1
    get_it: ^7.6.7
    bloc: ^8.1.3
    flutter_bloc: ^8.1.4
    equatable: ^2.0.5
    dartz: ^0.10.1
    flutter_widget_from_html: ^0.14.11
    cached_network_image: ^3.3.1
    xml: ^6.5.0
    url_launcher: ^6.2.5
    shimmer: ^3.0.0
    just_audio: ^0.9.36
    just_audio_background: ^0.0.1-beta.11
    path: ^1.9.0
    path_provider: ^2.1.2
    flutter_downloader: ^1.11.6
    sqflite: ^2.3.2
    package_info_plus: ^4.2.0
    permission_handler: ^11.3.0
    shared_preferences: ^2.2.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.1

flutter:
    uses-material-design: true

    assets:
        - assets/
        - assets/images/
